#!/bin/sh -e

# Static variables
DISTRIBUTIONS="wheezy"
FLAVOURS="-flujos"

# Dynamic variables
ARCHITECTURE="i386"
DATE=$(date +%Y%m%d)
VERSION=0.1a
NAME="ctp-radio-${VERSION}-${DISTRIBUTIONS}-${ARCHITECTURE}"
ISOHYBRID_OPTS="-entry 4 -type 1c"
EXT=iso
FNAME="${NAME}.${EXT}"

lb build noauto ${@} 2>&1 | tee ${FNAME}.log
