#!/bin/sh
set -e

BOOTAPPEND="boot=live config username=operadoris locales=es_AR.UTF-8 keyboard-layout=latama"
# menu config

MIRROR_DEBIAN="http://10.254.127.76:3142/debian/"
MIRROR_BINARY="http://cdn.debian.net/debian/"

    #--mirror-debian-installer http://localhost:9999/acervo \
    #--categories "main contrib non-free" \
    #--apt-secure disabled \

lb config noauto \
    --debian-installer live \
    --debian-installer-distribution wheezy \
    --debian-installer-gui false \
    --win32-loader true \
    --distribution wheezy \
    --architecture i386 \
    --archive-areas "main contrib non-free" \
    --mirror-bootstrap ${MIRROR_DEBIAN} \
    --mirror-chroot ${MIRROR_DEBIAN} \
    --mirror-binary ${MIRROR_BINARY} \
    --mirror-debian-installer ${MIRROR_DEBIAN} \
    --mode debian \
    --security false \
    --apt-recommends true \
    --apt-indices false \
    --linux-flavours 486 \
    --linux-packages "linux-image linux-headers" \
    --bootappend-live $BOOTAPPEND \
    --bootappend-install $BOOTAPPEND \
    --iso-application "CTP-Radio" \
    --iso-volume "ctp-radio" \
    --iso-publisher "http://ctpcordoba.blogspot.com.ar/" \
    --memtest memtest86+ \
    ${@}
